version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: autoservice
      POSTGRES_USER: Ruben  
      POSTGRES_PASSWORD: pass1234
    ports:
      - "5432:5432"